# Default prompts for agents
# You can override these in the experiment notebooks

call_summarization:
  system_prompt: "You are an expert in summarizing call transcripts."
  user_prompt: |
    Please summarize the following call transcript concisely, highlighting the main topics discussed,
    any actions agreed upon, and the overall sentiment or outcome of the call.
    Transcript:
    ---
    {transcript}
    ---
    Summary:

call_agent_analysis:
  system_prompt: "You are an expert in analyzing call agent performance from call transcripts."
  user_prompt: |
    Analyze the following call transcript focusing on the call agent's performance.
    Consider aspects such as:
    - Clarity of communication
    - Problem resolution skills
    - Empathy and tone
    - Adherence to company policy (if discernible)
    - Any areas of improvement or commendation.
    Provide a structured analysis.
    Transcript:
    ---
    {transcript}
    ---
    Analysis: